In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("./data/original_data/train.csv")
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
data["Age"] = data["Age"].fillna(-1)
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  -1.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
data = data.drop(['Name','SibSp','Parch'], axis = 1)
data

PassengerId  Survived  Pclass     Sex   Age            Ticket     Fare  \
0              1         0       3    male  22.0         A/5 21171   7.2500   
1              2         1       1  female  38.0          PC 17599  71.2833   
2              3         1       3  female  26.0  STON/O2. 3101282   7.9250   
3              4         1       1  female  35.0            113803  53.1000   
4              5         0       3    male  35.0            373450   8.0500   
..           ...       ...     ...     ...   ...               ...      ...   
886          887         0       2    male  27.0            211536  13.0000   
887          888         1       1  female  19.0            112053  30.0000   
888          889         0       3  female  -1.0        W./C. 6607  23.4500   
889          890         1       1    male  26.0            111369  30.0000   
890          891         0       3    male  32.0            370376   7.7500   

    Cabin Embarked  
0     NaN        S  
1     C85        C  
2     NaN        S  
3    C123        S  
4     NaN        S  
..    ...      ...  
886   NaN        S  
887   B42        S  
888   NaN        S  
889  C148        C  
890   NaN        Q  

[891 rows x 9 columns]

In [5]:
data = data.drop(['PassengerId','Ticket','Cabin'], axis = 1)
data

Survived  Pclass     Sex   Age     Fare Embarked
0           0       3    male  22.0   7.2500        S
1           1       1  female  38.0  71.2833        C
2           1       3  female  26.0   7.9250        S
3           1       1  female  35.0  53.1000        S
4           0       3    male  35.0   8.0500        S
..        ...     ...     ...   ...      ...      ...
886         0       2    male  27.0  13.0000        S
887         1       1  female  19.0  30.0000        S
888         0       3  female  -1.0  23.4500        S
889         1       1    male  26.0  30.0000        C
890         0       3    male  32.0   7.7500        Q

[891 rows x 6 columns]

In [6]:
def fn(x):
    if x:
        return (0, 1)
    else:
        return (1, 0)

data['Survived'] = data['Survived'].map(fn)
data

Survived  Pclass     Sex   Age     Fare Embarked
0     (1, 0)       3    male  22.0   7.2500        S
1     (0, 1)       1  female  38.0  71.2833        C
2     (0, 1)       3  female  26.0   7.9250        S
3     (0, 1)       1  female  35.0  53.1000        S
4     (1, 0)       3    male  35.0   8.0500        S
..       ...     ...     ...   ...      ...      ...
886   (1, 0)       2    male  27.0  13.0000        S
887   (0, 1)       1  female  19.0  30.0000        S
888   (1, 0)       3  female  -1.0  23.4500        S
889   (0, 1)       1    male  26.0  30.0000        C
890   (1, 0)       3    male  32.0   7.7500        Q

[891 rows x 6 columns]

In [7]:
def fn(x):
    if x == 'male':
        return 1
    else:
        return 0

data['Sex'] = data['Sex'].map(fn)
data

Survived  Pclass  Sex   Age     Fare Embarked
0     (1, 0)       3    1  22.0   7.2500        S
1     (0, 1)       1    0  38.0  71.2833        C
2     (0, 1)       3    0  26.0   7.9250        S
3     (0, 1)       1    0  35.0  53.1000        S
4     (1, 0)       3    1  35.0   8.0500        S
..       ...     ...  ...   ...      ...      ...
886   (1, 0)       2    1  27.0  13.0000        S
887   (0, 1)       1    0  19.0  30.0000        S
888   (1, 0)       3    0  -1.0  23.4500        S
889   (0, 1)       1    1  26.0  30.0000        C
890   (1, 0)       3    1  32.0   7.7500        Q

[891 rows x 6 columns]

In [8]:
data['Embarked'] = data['Embarked'].fillna('N')

k = set()
for i in data['Embarked']:
    k.add(i)
k

{'C', 'N', 'Q', 'S'}

In [9]:
def fn(x):
    if x == 'S':
        return 1
    elif x == 'C':
        return 2
    elif x == 'Q':
        return 3
    elif x == 'N':
        return 4
    
data['Embarked'] = data['Embarked'].map(fn)
data

Survived  Pclass  Sex   Age     Fare  Embarked
0     (1, 0)       3    1  22.0   7.2500         1
1     (0, 1)       1    0  38.0  71.2833         2
2     (0, 1)       3    0  26.0   7.9250         1
3     (0, 1)       1    0  35.0  53.1000         1
4     (1, 0)       3    1  35.0   8.0500         1
..       ...     ...  ...   ...      ...       ...
886   (1, 0)       2    1  27.0  13.0000         1
887   (0, 1)       1    0  19.0  30.0000         1
888   (1, 0)       3    0  -1.0  23.4500         1
889   (0, 1)       1    1  26.0  30.0000         2
890   (1, 0)       3    1  32.0   7.7500         3

[891 rows x 6 columns]

In [12]:
inputs = []
for i, row in enumerate(data.max()):
    if i :
        row = float(row)
        print(type(row),row)
        inputs.append(row)
print(np.array(inputs))
np.array(inputs)

<class 'float'> 3.0
<class 'float'> 1.0
<class 'float'> 80.0
<class 'float'> 512.3292
<class 'float'> 4.0
[  3.       1.      80.     512.3292   4.    ]


array([  3.    ,   1.    ,  80.    , 512.3292,   4.    ])

In [13]:
inputs = []
for i, row in enumerate(data.min()):
    if i :
        row = float(row)
        print(type(row),row)
        inputs.append(row)
print(np.array(inputs))
np.array(inputs)

<class 'float'> 1.0
<class 'float'> 0.0
<class 'float'> -1.0
<class 'float'> 0.0
<class 'float'> 1.0
[ 1.  0. -1.  0.  1.]


array([ 1.,  0., -1.,  0.,  1.])

In [10]:
data.loc[3]

Survived    (0, 1)
Pclass           1
Sex              0
Age             35
Fare          53.1
Embarked         1
Name: 3, dtype: object

In [11]:
inputs = []
for i, row in enumerate(data.loc[3]):
    if not i :
        print(type(row),row)
        labels = [*row]
    else:
        print(type(row),row)
        inputs.append(row)
print(np.array(labels))
print(np.array(inputs))

<class 'tuple'> (0, 1)
<class 'numpy.int64'> 1
<class 'numpy.int64'> 0
<class 'numpy.float64'> 35.0
<class 'numpy.float64'> 53.1
<class 'numpy.int64'> 1
[0 1]
[ 1.   0.  35.  53.1  1. ]


In [12]:
inputs = []
for i, row in enumerate(data.loc[3]):
    if not i :
        print(type(row),row)
        labels = [*row]
    else:
        row = float(row)
        print(type(row),row)
        inputs.append(row)
print(np.array(labels))
print(np.array(inputs))

<class 'tuple'> (0, 1)
<class 'float'> 1.0
<class 'float'> 0.0
<class 'float'> 35.0
<class 'float'> 53.1
<class 'float'> 1.0
[0 1]
[ 1.   0.  35.  53.1  1. ]


In [13]:
def get_single_row(i):
    inputs = []
    for k, row in enumerate(data.loc[i]):
        if not k :
            labels = [*row]
        else:
            inputs.append(float(row))
    return np.array(inputs).astype(np.float32), np.array(labels).astype(np.float32)

In [14]:
np.array(data.loc[3][1:])

array([1, 0, 35.0, 53.1, 1], dtype=object)

In [15]:
import tensorflow as tf

In [16]:
num_of_rows = len(data)

with tf.io.TFRecordWriter(
    './data/TFRs/train.tfrecord'     #-{0:05d}-of-{1:05d}'.format(i, num_of_files)
) as file_writer:
    i = 0
    while i < num_of_rows:
        x, y = get_single_row(i)
        x = tf.io.serialize_tensor(x).numpy()
        y = tf.io.serialize_tensor(y).numpy()

        record_bytes = \
        tf.train.Example(features=tf.train.Features(feature={
            "inputs": tf.train.Feature(bytes_list=tf.train.BytesList(value=[x])),
            "labels": tf.train.Feature(bytes_list=tf.train.BytesList(value=[y])),
        })).SerializeToString()
        file_writer.write(record_bytes)
        i += 1

In [ ]:
data = pd.read_csv("./data/original_data/train.csv")
data["Age"] = data["Age"].fillna(-1)
data = data.drop(['Name','SibSp','Parch'], axis = 1)
def fn(x):
    if x:
        return (0, 1)
    else:
        return (1, 0)

data['Survived'] = data['Survived'].map(fn)
data['Embarked'] = data['Embarked'].fillna('N')
def fn(x):
    if x == 'male':
        return 1
    else:
        return 0

data['Sex'] = data['Sex'].map(fn)
def fn(x):
    if x == 'S':
        return 1
    elif x == 'C':
        return 2
    elif x == 'Q':
        return 3
    elif x == 'N':
        return 4
    
data['Embarked'] = data['Embarked'].map(fn)
data = data.drop(['PassengerId','Ticket','Cabin'], axis = 1)

In [14]:
891/32

27.84375